data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 5
    wrap: false
    validation:
      target: ldm.data.slice_dataset_infer_28class_randomclass.slice_val
      params:
        data_root: '/storage/chenqi/data/our_data/nnUNet_preprocessed/'
        data_name: 'Dataset010_MSD_Liver'